#!/bin/zsh
#
# Configures    System Theme, Dock, Trackpad, Screenshots
# Uninstalls    iMovie, GarageBand
# Installs      Geekbench, Bitwarden, Signal, Proton Mail
emulate -LR zsh # reset zsh options

# path of currently executing script
DIR=${0:a:h}
# import common libraries
source $DIR/../lib/console_codes.zsh
source $DIR/../lib/getopts.zsh

# check for homebrew and updates if software installs will occur
# if ! should_skip "geekbench" && \
#    ! should_skip "bitwarden" && \
#    ! should_skip "signal" && \
#    ! should_skip "protonmail"; then
#     source $DIR/../lib/brew_check.zsh
# fi

restart_required=false

########
# Theme
########
if should_skip "theme"; then
    echo -e "\nSkipping ${bold}System Theme${reset} configuration"
else
    echo -e "\nSetting system theme."

    # Close open System Preferences panes, to prevent them from overriding settings.
    osascript -e 'tell application "System Preferences" to quit'
    # disable automatic theme switching 
    defaults write NSGlobalDomain AppleInterfaceStyleSwitchesAutomatically -bool true
    defaults delete NSGlobalDomain AppleInterfaceStyleSwitchesAutomatically
    # Set the system theme to dark
    defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
    # UI must restart for changes to take effect
    if [ "$force" = true ]; then
        restart_required=true
        echo "${pink_f}System must restart for theme change to take effect.${reset}"
    else
        echo -e "\n${bold}Attention${reset}:"
        echo "macOS may request permission to control 'System Events' in order to set dark mode."
        # echo without newline
        echo -n "Press any key when ready.."
        read -k -s
        # terminal escape - ^^ delete everything on current line 
        echo -e "\033[2K"
        osascript -l JavaScript -e "Application('System Events').appearancePreferences.darkMode = true" >/dev/null
    fi

    echo "${green_f}${bold}System Theme${reset}${green_f} has been set.${reset}"

fi

#######
# Dock
#######

###########
# Trackpad
###########
if should_skip "trackpad"; then
    echo -e "\nSkipping ${bold}Trackpad${reset} configuration"
else
    echo -e "\nSetting Trackpad preferences"
    # enable tap to click
    defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
    # TODO: for some reason the checkbox isn't checked, but it works

    # set the click force
    defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
    defaults write com.apple.AppleMultitouchTrackpad SecondClickThreshold -int 0

    # set cursor tracking speed (scale of 0-3)
    # [0, 0.125, 0.5, 0.6875, 0.875, 1, 1.5, 2, 2.5, 3]
    defaults write NSGlobalDomain com.apple.trackpad.scaling 2.5

    # TODO: can't figure out which process to restart to have changes take effect
    restart_required=true
    echo "${pink_f}System must restart for trackpad preferences to take effect.${reset}"

    echo "${green_f}${bold}Trackpad${reset}${green_f} preferences have been set.${reset}"

fi

#################
# screenshot.app
#################

if $restart_required; then
    echo -e "\n${bold}Note${reset}: Some changes require a ${pink_f}logout and/or restart${reset} to take effect"
fi
# leave space above next terminal prompt for readability
echo ""
